/**
 * Root frequency aggregates for the `/frequency` page.
 *
 * `public/data/root-frequency.json` is generated by
 * `scripts/analyze-root-distribution.ts` (`npm run data:root-dist`) from the
 * QAC morphology file, and committed. It is imported rather than read with
 * `fs` so it lands in the server bundle and the page renders identically
 * whether it is prerendered at build time or served dynamically — `public/`
 * is not reliably readable from a serverless filesystem at runtime.
 *
 * The import stays server-side: `RootFrequencyView` is a Server Component and
 * ships only its rendered HTML, so none of these ~138 KB reach the browser.
 * Keep it that way — adding `"use client"` anywhere up this chain would push
 * the whole payload into the client bundle.
 */
import report from "@/public/data/root-frequency.json";

/** One of the five rank bands the leaderboard groups by. */
export interface FrequencyTier {
  /** Stable key for the i18n label — `tier1` … `tier5`. */
  label: string;
  lo: number;
  hi: number;
  words: number;
  share: number;
  /** Lowest occurrence count inside the tier. */
  floor: number;
}

export interface FrequencyRow {
  rank: number;
  bare: string;
  translit: string;
  gloss: string | null;
  count: number;
  surahs: number;
  verses: number;
  forms: number;
  share: number;
  cumShare: number;
}

export interface NameEntry {
  rank: number;
  bare: string;
  translit: string;
  gloss: string | null;
  count: number;
  surahs: number;
  verses: number;
  first: { sura: number; ayah: number } | null;
  /** Multi-word phrase whose occurrences overlap a single-word entry. */
  phrase: boolean;
}

/**
 * Proper nouns. The corpus tags them separately because they carry no root,
 * so none of their occurrences sit inside the root-bearing word count.
 *
 * `occurrences` covers the single-word names only: the four compound phrases
 * are counted apart because each one's occurrences are a SUBSET of a
 * single-word entry wherever one exists — بني إسرائيل (27×) is 27 of
 * إسرائيل's 43 — so adding the two totals would count those words twice.
 */
export interface NameBlock {
  total: number;
  singles: number;
  compounds: number;
  occurrences: number;
  entries: NameEntry[];
}

export interface RootFrequencyReport {
  version: number;
  generated: string;
  totals: { roots: number; words: number; hapax: number; median: number; mean: number };
  tiers: FrequencyTier[];
  coverage: { rank: number; words: number; share: number; minCount: number }[];
  buckets: { lo: number; hi: number | null; roots: number; words: number }[];
  ties: { count: number; n: number; members: { bare: string; gloss: string | null; surahs: number }[] }[];
  bands: {
    lo: number;
    hi: number;
    focus: boolean;
    members: { bare: string; count: number; surahs: number; gloss: string | null }[];
  }[];
  leaderboard: FrequencyRow[];
  scatter: { bare: string; gloss: string | null; count: number; surahs: number; topShare: number; topSura: number }[];
  names: NameBlock;
}

export const ROOT_FREQUENCY = report as unknown as RootFrequencyReport;

/** Tier index (1-based) for a rank — drives the CSS-only "Top N" filter. */
export function tierOf(rank: number, tiers: FrequencyTier[]): number {
  const i = tiers.findIndex((t) => rank >= t.lo && rank <= t.hi);
  return i === -1 ? tiers.length : i + 1;
}
